kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-webserver
spec:
  replicas: 2
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: go-app-container
          image: hello:1.0.0
          resources:
            limits:
              memory: "32Mi"
              cpu: "120M"
          ports:
          - containerPort: 8080
